### ISSUE TITLE
How do I train a classifier using the API?

### ISSUE THREAD

**Issue by jonas-schulze** [monkeylearn/monkeylearn-ruby#16]
[With the v2 API it was possible to start a training](https://monkeylearn.com/api/v2/#train) using `Monkeylearn.classifiers.train classifier_key`, but the [API reference](https://monkeylearn.com/api/v3/) does not mention this endpoint anymore. Is there a reason you removed it? Will it be added again someway down the road?

**Comment by gonz** [comment]
Hey @jonas-schulze 

The new MonkeyLearn release automatically trains your models when a change is detected, that's why the *Train* button is gone from the [MonkeyLearn UI](https://app.monkeylearn.com/) and the [MonkeyLearn v3.0 API](https://monkeylearn.com/api/v3/).

There's no plan to add it at the moment since it's no longer needed to explicitly request a train but we are closely following the UI and API usage and listening to user feedback.

New endpoints to track the state of an on going train session or check if a classifier is marked for train might be added in the future. The `last_trained` field in the [classifier detail](https://monkeylearn.com/api/v3/#classifier-detail) should do the trick for most use cases.

Also note that all this applies to the new custom extractors.
