### ISSUE TITLE
Category list endpoint?

### ISSUE THREAD

**Issue by harlow** [monkeylearn/monkeylearn-ruby#3]
We have access to Create, Edit, and Delete for categories:
https://github.com/monkeylearn/monkeylearn-ruby/blob/2148a2242085ffb6b0c9c18b263cef100cb28e04/lib/monkeylearn/classifiers.rb#L111-L135

But is there a way to list them all? When using the classifier it's required to have a "root_category_id" so without a list of the categories its hard to determine what the ID of a category is.

How do you feel about adding `Monkeylearn.classifiers.categories.list` that returns all the categories for the classifier

**Comment by gonz** [comment]
Currently you can get all project categories using the project detail endpoint (`Monkeylearn.classifiers.detail`). We may definitively add a `Monkeylearn.classifiers.categories.list` endpoint in the future for completeness but since you can already do it with the mentioned endpoint it's not currently a priority to implement it. HTH
